/**
 * =====================================================
 * Copyright © sumu. 2022-present. Tech. Co., Ltd. All rights reserved.
 * File name  : init-templates.ts
 * Author     : sumu
 * Date       : 2026/08/28
 * Version    : x.x.x
 * Description: init 命令的内嵌模板（单文件 exe 模式的模板来源）
 *
 * ⚠️ 本文件由 scripts/gen-init-templates.mjs 自动生成，请勿手改。
 *    修改仓库模板后执行 npm run gen:init-templates 重新生成。
 *
 * 用途：打包成单文件 exe 后没有磁盘模板目录，init 改为运行时把这些内嵌
 * 模板写出（见 init.ts 的 writeEmbeddedTemplates）。内容与仓库根目录下的
 * 同名模板文件逐字节一致（content 按源文件行逐行书写，join("") 还原，
 * 便于阅读与 diff）。例外：.opencode/opencode.json 在生成时剔除了
 * instructions 字段（exe 模式不生成其指向的 .claude/CLAUDE.md）。
 * .mcp.json / opencode.json / remote-start-mcp.bat 在写出时会适配 exe
 * 入口（命令替换为 embedded-mcp-toolkit.exe）。
 * ======================================================
 */

/** 内嵌模板条目：dest 为相对目标目录的写出路径，content 为文件内容 */
export interface EmbeddedTemplate {
  dest: string;
  content: string;
}

/** 全部内嵌模板（生成时间戳：2026-08-28T01:20:29.161Z） */
export const EMBEDDED_TEMPLATES: EmbeddedTemplate[] = [
  {
    dest: ".mcp.json",
    content: [
      "{\n",
      "  \"$schema\": \"https://json.schemastore.org/claude-code-settings.json\",\n",
      "  \"mcpServers\": {\n",
      "    \"embedded-board\": {\n",
      "      \"command\": \"node\",\n",
      "      \"args\": [\n",
      "        \"./bin/embedded-mcp-toolkit-cli.js\"\n",
      "      ],\n",
      "      \"env\": {\n",
      "        \"DEVICE\": \"board-b\",\n",
      "        \"BOARD_CONFIG_PATH\": \"./.embedded/configs/config.yaml\",\n",
      "        \"LOG_SAVE\": \"1\",\n",
      "        \"LOG_DIR\": \"./.embedded/log\",\n",
      "        \"SAVE2FILE_PATH\": \"./.embedded/log\"\n",
      "      }\n",
      "    },\n",
      "    \"file_utils_remote\": {\n",
      "      \"command\": \"ssh\",\n",
      "      \"args\": [\n",
      "        \"-i\", \"~/.ssh/id_file_utils_remote\",\n",
      "        \"-o\", \"ServerAliveInterval=60\",\n",
      "        \"sumu@192.168.164.128\",\n",
      "        \"PATH=$HOME/.npm-global/bin:$PATH file-utils-mcp-toolkit\"\n",
      "      ]\n",
      "    }\n",
      "  }\n",
      "}\n",
    ].join(""),
  },
  {
    dest: ".opencode/opencode.json",
    content: [
      "{\n",
      "  \"$schema\": \"https://opencode.ai/config.json\",\n",
      "  \"mcp\": {\n",
      "    \"embedded-board\": {\n",
      "      \"type\": \"local\",\n",
      "      \"command\": [\n",
      "        \"node\",\n",
      "        \"./bin/embedded-mcp-toolkit-cli.js\"\n",
      "      ],\n",
      "      \"enabled\": true,\n",
      "      \"timeout\": 600000,\n",
      "      \"environment\": {\n",
      "        \"DEVICE\": \"board-b\",\n",
      "        \"BOARD_CONFIG_PATH\": \"./.embedded/configs/config.yaml\",\n",
      "        \"LOG_SAVE\": \"1\",\n",
      "        \"LOG_DIR\": \"./.embedded/log\",\n",
      "        \"SAVE2FILE_PATH\": \"./.embedded/log\"\n",
      "      }\n",
      "    },\n",
      "    \"file_utils_remote\": {\n",
      "      \"type\": \"local\",\n",
      "      \"command\": [\n",
      "        \"ssh\",\n",
      "        \"-i\",\n",
      "        \"~/.ssh/id_file_utils_remote\",\n",
      "        \"-o\",\n",
      "        \"ServerAliveInterval=60\",\n",
      "        \"sumu@192.168.164.128\",\n",
      "        \"PATH=$HOME/.npm-global/bin:$PATH file-utils-mcp-toolkit\"\n",
      "      ],\n",
      "      \"enabled\": true,\n",
      "      \"timeout\": 600000\n",
      "    }\n",
      "  }\n",
      "}\n",
    ].join(""),
  },
  {
    dest: ".claude/settings.local.json",
    content: [
      "{\n",
      "  \"permissions\": {\n",
      "    \"allow\": [\n",
      "      \"mcp__embedded-board__device_info_tool\",\n",
      "      \"mcp__embedded-board__ssh_shell_login\",\n",
      "      \"mcp__embedded-board__ssh_shell_connection\",\n",
      "      \"mcp__embedded-board__ssh_shell_close\",\n",
      "      \"mcp__embedded-board__serial_shell_login\",\n",
      "      \"mcp__embedded-board__serial_close\",\n",
      "      \"mcp__embedded-board__serial_exec\",\n",
      "      \"mcp__embedded-board__network_scan_tool\",\n",
      "      \"mcp__embedded-board__port_scan_tool\",\n",
      "      \"mcp__embedded-board__session_info\",\n",
      "      \"mcp__embedded-board__serial_enter_uboot\"\n",
      "    ]\n",
      "  },\n",
      "  \"enabledMcpjsonServers\": [\n",
      "    \"embedded-board\",\n",
      "    \"file_utils_remote\"\n",
      "  ],\n",
      "  \"statusLine\": {\n",
      "    \"type\": \"command\",\n",
      "    \"command\": \"npx -y ccstatusline --config .claude/ccstatusline-settings.json\",\n",
      "    \"padding\": 0,\n",
      "    \"refreshInterval\": 5\n",
      "  }\n",
      "}\n",
    ].join(""),
  },
  {
    dest: ".embedded/configs/config.example.yaml",
    content: [
      "# ============================================\n",
      "# embedded-mcp-toolkit 设备配置文件模板\n",
      "# 复制并修改: cp config.example.yaml config.yaml\n",
      "# ============================================\n",
      "\n",
      "# 默认使用的设备（对应 devices/ 目录下的文件名，去掉 .yaml 扩展名）\n",
      "default: board-example\n",
      "\n",
      "# ============================================\n",
      "# 全局 exec 超时配置（所有设备共享，设备级可覆盖）\n",
      "# ============================================\n",
      "# 用于交互式 shell exec（adb/ssh/serial 三通道共享）的常驻命令分类与超时时长。\n",
      "# 所有板子生效，无需每台设备重复配置。设备级 devices.<name> 下同名字段可覆盖：\n",
      "#   - samplingTimeoutMs / fallbackTimeoutMs：设备级优先（覆盖语义）\n",
      "#   - residentCommands：全局 ∪ 设备级（并集，白名单累加）\n",
      "# execTimeout:\n",
      "#   # 常驻命令扩展名单（首 token 精确匹配），与内置白名单(ping/logcat/top/...)并集。\n",
      "#   # 留空则仅用内置白名单。用于适配项目特有的持续输出命令。\n",
      "#   residentCommands:\n",
      "#     - my_log_streamer\n",
      "#     - custom_top_like\n",
      "#\n",
      "#   # 常驻命令采样超时（毫秒）：ping/logcat/top 等的默认执行时长，到点发 Ctrl+C 采样。\n",
      "#   # 留空默认 10000（10 秒）。\n",
      "#   samplingTimeoutMs: 10000\n",
      "#\n",
      "#   # 普通命令兜底超时（毫秒）：提示符正则未匹配时的安全阀，到点不发 Ctrl+C。\n",
      "#   # 留空默认 300000（5 分钟）。\n",
      "#   fallbackTimeoutMs: 300000\n",
      "\n",
      "# ============================================\n",
      "# 设备配置说明\n",
      "# ============================================\n",
      "# 每台设备的完整配置存放在同级 devices/ 目录下的独立文件中，\n",
      "# 一个 .yaml 文件对应一台设备，文件名即设备名。\n",
      "#\n",
      "# 目录结构示例：\n",
      "#   .embedded/configs/\n",
      "#   ├── config.yaml              ← 本文件：放 default 等全局设置（下方也内联了 1 个示例设备）\n",
      "#   └── devices/\n",
      "#       ├── board-a.yaml         ← 设备 a 的完整配置（ssh/serial/adb/keyProvider）\n",
      "#       └── board-b.yaml         ← 设备 b 的完整配置\n",
      "#\n",
      "# 单个设备文件的内容形如：\n",
      "#   ssh:\n",
      "#     host: \"192.168.16.103\"\n",
      "#     port: 22\n",
      "#     keyProvider: { ... }\n",
      "#   serial:\n",
      "#     port: \"COM4\"\n",
      "#     baudRate: 115200\n",
      "#   adb:\n",
      "#     serialNo: \"sn_none\"\n",
      "#   promptPattern: \"...\"  # 可选，设备级 exec 提示符正则（与 ssh/serial/adb 平级，见下方说明）\n",
      "#\n",
      "# ── promptPattern（exec 提示符检测，可选）──\n",
      "# *_shell_exec（adb/ssh/serial）轮询输出检测 shell 提示符以判断命令结束，三通道共享同一正则。\n",
      "# 留空则用内置默认正则（已覆盖 Android :/ $、Linux $/#/>、U-Boot => 等常见提示符）。\n",
      "# 仅当设备自定义 PS1 且默认正则不命中时才配置；正则按 JavaScript RegExp 语法，new RegExp() 构造。\n",
      "# 注意层级差异：\n",
      "#   - 分文件布局（devices/<设备名>.yaml）：写在设备文件根层，与 adb/ssh/serial 平级\n",
      "#   - 单文件布局（本文件 devices 段）：写在 devices.<设备名> 下，与 adb/ssh/serial 平级（缩进 4 格）\n",
      "# 示例见下方 board-example 内联段（已注释）。\n",
      "#\n",
      "# 加载优先级（重要）：\n",
      "#   当 devices/ 目录存在且非空时：\n",
      "#     - 设备配置「只看 devices/*.yaml」，本文件下方的 devices 段被完全忽略（不报错、不合并）。\n",
      "#     - 修改设备请改 devices/<设备名>.yaml，改本文件 devices 段无效。\n",
      "#   当 devices/ 目录不存在或为空时：\n",
      "#     - 回退读取本文件下方的 devices 段。\n",
      "#   无论哪种情况，default 等全局字段始终从本文件读取。\n",
      "#\n",
      "# 两种布局取舍：\n",
      "#   - 设备少（1~2 台）：可直接用本文件下方的 devices 段，无需 devices/ 目录。\n",
      "#   - 设备多：用 devices/ 目录拆分，每台一个文件，本文件 devices 段可清空。\n",
      "#   - 两者并存时以 devices/ 为准（见上方加载优先级）。\n",
      "#\n",
      "# 如需从旧的单文件布局迁移，运行：\n",
      "#   embedded-mcp-toolkit split\n",
      "\n",
      "# ============================================\n",
      "# 通道启用/禁用约定\n",
      "# ============================================\n",
      "#   ssh 段    host 设为 \"none\" → 该设备不启用 SSH（调用 ssh 工具会返回 \"does not support SSH\"）\n",
      "#   serial 段 port 设为 \"none\" → 该设备不启用串口（调用 serial 工具会返回 \"does not support serial\"）\n",
      "#   adb 段    serialNo 设为 \"sn_none\" 或留空 → 不绑定具体 ADB 设备，由 adb 自动发现\n",
      "# 不需要的通道可直接整段删除，或保留段并把关键字段置 \"none\"/\"sn_none\"。\n",
      "\n",
      "# ============================================\n",
      "# 示例设备（内联于本文件，无需 devices/ 目录即可使用）\n",
      "# ============================================\n",
      "# 注意：本段仅在 devices/ 目录「不存在或为空」时生效。\n",
      "#       一旦 devices/ 目录存在且非空，本段被完全忽略，改这里无效。\n",
      "#       设备多时建议改用 devices/ 目录，并删除本段。\n",
      "devices:\n",
      "  board-example:\n",
      "    # promptPattern: \"(?:\\\\[[0-9]+\\\\][^\\r\\n]*[#$]\\s*)$\" # 设备级 exec 提示符正则（与 adb/ssh/serial 平级）；留空用默认正则。例：匹配 [130]root@host:~#\n",
      "    adb:\n",
      "      serialNo: \"sn_none\" # ADB 设备序列号，sn_<序列号> 或 sn_none 表示未配置\n",
      "    ssh:\n",
      "      host: \"192.168.16.105\" # SSH 主机地址；设为 \"none\" 表示该设备不启用 SSH\n",
      "      port: 22 # SSH 端口，默认 22\n",
      "      username: \"root\" # SSH 登录用户名\n",
      "      password: \"root\" # 密码认证（与 privateKey 二选一）\n",
      "      keyProvider:\n",
      "        mode: \"file\" # file: 通过文件 IPC 获取密钥; terminal: 终端交互输入\n",
      "        # ↓↓↓ 路径基准说明 ↓↓↓\n",
      "        # challengeFilePath / keyFilePath 是「相对于运行 MCP server 时的工作目录（cwd）」的路径，\n",
      "        # 而非相对于本设备文件或 config.yaml 的位置。\n",
      "        # 通常 MCP server 在项目根目录启动，故写 ./ 开头的项目相对路径即可。\n",
      "        challengeFilePath: \"./.embedded/configs/challenge.txt\" # 挑战信息写入文件路径（相对 cwd）\n",
      "        keyFilePath: \"./.embedded/configs/password_input.txt\" # 轮询密钥的文件路径（相对 cwd）\n",
      "        pollInterval: 500 # 轮询间隔（毫秒）\n",
      "        timeout: 120000 # 超时（毫秒），默认 2 分钟\n",
      "    serial:\n",
      "      port: \"COM3\" # 串口设备路径（如 COM3、/dev/ttyUSB0）；设为 \"none\" 表示该设备不启用串口\n",
      "      baudRate: 115200 # 波特率，默认 115200\n",
      "      loginUsername: \"root\" # 串口登录用户名\n",
      "      loginPassword: \"root\" # 串口登录密码\n",
      "      keyProvider:\n",
      "        mode: \"file\"\n",
      "        challengeFilePath: \"./.embedded/configs/challenge.txt\" # 相对 cwd\n",
      "        keyFilePath: \"./.embedded/configs/password_input.txt\" # 相对 cwd\n",
      "        pollInterval: 500\n",
      "        timeout: 120000\n",
      "      # uboot 子段（serial_enter_uboot 检测配置，全部可选，留空用默认值）。\n",
      "      # 字段值直接写 JavaScript 正则源码字符串（双引号中反斜杠双写，详见 docs/regex-guide.md）。\n",
      "      # 详细示例见 devices/board-example.yaml。\n",
      "      uboot:\n",
      "        autobootPrompts: # 含 \"Ctrl+u\" 字样的条目 → 发 \\x15；其余 → 发换行\n",
      "          - \"Hit\\\\s+Ctrl\\\\+u\\\\s+to\\\\s+stop\\\\s+autoboot\"\n",
      "          - \"Hit\\\\s+any\\\\s+key\\\\s+to\\\\s+stop\\\\s+autoboot\"\n",
      "        # 命令提示符，命中即判成功（主层）。常见厂商：=> / Marvell>> / hisilicon# / STM32MP> / ZynqMP>\n",
      "        # 多板子共用配置时用联合正则，如 \"(?:=>|Marvell>>|hisilicon#)\\\\s*$\"\n",
      "        prompt: \"(?:=>|U-Boot>)\\\\s*$\"\n",
      "        verifyEnvKeys: # 提示符未命中时发 printenv 验证的环境变量键（纯字面量）\n",
      "          - \"baudrate\"\n",
      "          - \"bootdelay\"\n",
    ].join(""),
  },
  {
    dest: ".embedded/configs/config.yaml",
    content: [
      "# ============================================\n",
      "# embedded-mcp-toolkit 设备配置文件模板\n",
      "# 复制并修改: cp config.example.yaml config.yaml\n",
      "# ============================================\n",
      "\n",
      "# 默认使用的设备（对应 devices 下的 key）\n",
      "default: board-a\n",
      "\n",
      "# ============================================\n",
      "# 全局 exec 超时配置（所有设备共享，设备级可覆盖）\n",
      "# ============================================\n",
      "# 用于交互式 shell exec（adb/ssh/serial 三通道共享）的常驻命令分类与超时时长。\n",
      "# 设备级 devices.<name> 下同名字段可覆盖（时长：设备级优先；residentCommands：全局∪设备级并集）。\n",
      "execTimeout:\n",
      "  # 常驻命令扩展名单（首 token 精确匹配），与内置白名单(ping/ping6/logcat/top/htop/strace/tcpdump/watch，\n",
      "  # 以及 dmesg -w / journalctl -f / tail -f 等带 follow 参数的命令)并集。\n",
      "  # 留空则仅用内置白名单。用于适配项目特有的持续输出命令。\n",
      "  # residentCommands:\n",
      "  #   - my_log_streamer\n",
      "\n",
      "  # 常驻命令采样超时（毫秒）：ping/logcat/top 等的默认执行时长，到点发 Ctrl+C 采样。\n",
      "  # 留空默认 10000（10 秒）。\n",
      "  # samplingTimeoutMs: 10000\n",
      "\n",
      "  # 普通命令兜底超时（毫秒）：提示符正则未匹配时的安全阀，到点不发 Ctrl+C。\n",
      "  # 留空默认 300000（5 分钟）。\n",
      "  # fallbackTimeoutMs: 300000\n",
    ].join(""),
  },
  {
    dest: ".embedded/configs/devices/board-example.yaml",
    content: [
      "# ============================================\n",
      "# 设备配置示例（模板）\n",
      "# 文件名（board-example）即设备名，内容为该设备的完整、自包含配置\n",
      "# ============================================\n",
      "#\n",
      "# 通道启用/禁用约定：\n",
      "#   ssh 段    host 设为 \"none\" → 该设备不启用 SSH（调用 ssh 工具会返回 \"does not support SSH\"）\n",
      "#   serial 段 port 设为 \"none\" → 该设备不启用串口（调用 serial 工具会返回 \"does not support serial\"）\n",
      "#   adb 段    serialNo 设为 \"sn_none\" 或留空 → 不绑定具体 ADB 设备，由 adb 自动发现\n",
      "# 不需要的通道可直接整段删除，或保留段并把关键字段置 \"none\"/\"sn_none\"。\n",
      "#\n",
      "# exec 提示符检测约定：\n",
      "#   *_shell_exec（adb/ssh/serial）在执行命令后会轮询输出缓冲区，检测 shell 提示符\n",
      "#   以判断命令是否结束（结束则提前返回，不必等满 timeoutMs）。三通道共享同一正则。\n",
      "#\n",
      "#   promptPattern —— 设备级提示符正则，与下方 adb/ssh/serial 段平级（同属设备根层）。\n",
      "#   留空（或删除该行）则使用内置默认正则。\n",
      "#   默认正则已覆盖常见提示符，绝大多数设备无需配置：\n",
      "#     - Android :  :/ $ 、 :/ #\n",
      "#     - Linux   :  $ 、 # 、 >\n",
      "#     - U-Boot  :  => 、 U-Boot>\n",
      "#   仅当设备使用自定义 PS1 且默认正则不命中时才需要配置，例如：\n",
      "#     - 带 exit code 前缀的 PS1：[130]root@host:~# → 匹配数字+]\n",
      "#     - 自定义颜色/日期的 PS1：正则需兼顾 ANSI 转义码或固定前缀\n",
      "#   正则按 JavaScript RegExp 语法书写，内部会 new RegExp(promptPattern) 构造。\n",
      "#   未命中时由 exec 的超时机制兜底，不会挂死。\n",
      "#\n",
      "# exec 超时与常驻命令识别约定（三通道共享）：\n",
      "#   *_shell_exec 区分「常驻命令」与「普通命令」，采用不同的超时策略：\n",
      "#     - 常驻命令（ping/ping6/logcat/top/htop/strace/tcpdump/watch，以及 dmesg -w /\n",
      "#       journalctl -f / tail -f 等带 follow 参数的命令）：默认采样超时 10 秒，到点\n",
      "#       自动发 Ctrl+C 终止（中性采样语义），返回已收集的输出。\n",
      "#     - 普通命令：靠提示符检测在命令结束时返回；仅当提示符正则未匹配上时，走兜底超时\n",
      "#       （默认 5 分钟，不发 Ctrl+C），作为安全阀防止命令永久挂起。\n",
      "#   识别按命令行「首 token」判断（第一个空白/管道/重定向之前的命令名）。\n",
      "#\n",
      "#   配置归属：常驻命令扩展名单(residentCommands)、采样超时(samplingTimeoutMs)、\n",
      "#   兜底超时(fallbackTimeoutMs)均为「全局配置」，写在 config.yaml 根层的 execTimeout\n",
      "#   子段（所有设备共享，无需每台设备重复配置）。\n",
      "#   设备级覆盖（可选，与 promptPattern 平级写在本文件根层）：\n",
      "#     - samplingTimeoutMs / fallbackTimeoutMs：设备级优先（覆盖全局）\n",
      "#     - residentCommands：全局 ∪ 设备级（并集累加）\n",
      "#   详见 config.example.yaml 的 execTimeout 段说明。\n",
      "#\n",
      "# ↓↓↓ 设备级字段，与 adb/ssh/serial 平级（分文件布局写在设备文件根层）↓↓↓\n",
      "# promptPattern: \"(?:\\\\[[0-9]+\\\\][^\\r\\n]*[#$]\\s*)$\" # 例：匹配 [130]root@host:~# 这类带退出码前缀的 PS1\n",
      "# 设备级 exec 超时覆盖（可选，覆盖/追加全局 execTimeout；一般无需配置，留空用全局值）：\n",
      "# samplingTimeoutMs: 5000    # 仅本设备采样超时改为 5 秒\n",
      "# fallbackTimeoutMs: 60000   # 仅本设备兜底超时改为 1 分钟\n",
      "# residentCommands:           # 追加本设备特有的常驻命令（与全局并集）\n",
      "#   - my_board_specific_daemon\n",
      "\n",
      "adb:\n",
      "  serialNo: \"sn_none\" # ADB 设备序列号，sn_<序列号> 或 sn_none 表示未配置\n",
      "\n",
      "ssh:\n",
      "  host: \"192.168.16.105\" # SSH 主机地址；设为 \"none\" 表示该设备不启用 SSH\n",
      "  port: 22 # SSH 端口，默认 22\n",
      "  username: \"root\" # SSH 登录用户名\n",
      "  password: \"root\" # 密码认证（与 privateKey 二选一）\n",
      "  keyProvider:\n",
      "    mode: \"file\" # file: 通过文件 IPC 获取密钥; terminal: 终端交互输入\n",
      "    # ↓↓↓ 路径基准说明 ↓↓↓\n",
      "    # challengeFilePath / keyFilePath 是「相对于运行 MCP server 时的工作目录（cwd）」的路径，\n",
      "    # 而非相对于本设备文件或 config.yaml 的位置。\n",
      "    # 通常 MCP server 在项目根目录启动，故写 ./ 开头的项目相对路径即可。\n",
      "    challengeFilePath: \"./.embedded/configs/challenge.txt\" # 挑战信息写入文件路径（相对 cwd）\n",
      "    keyFilePath: \"./.embedded/configs/password_input.txt\" # 轮询密钥的文件路径（相对 cwd）\n",
      "    pollInterval: 500 # 轮询间隔（毫秒）\n",
      "    timeout: 120000 # 超时（毫秒），默认 2 分钟\n",
      "\n",
      "serial:\n",
      "  port: \"COM3\" # 串口设备路径（如 COM3、/dev/ttyUSB0）；设为 \"none\" 表示该设备不启用串口\n",
      "  baudRate: 115200 # 波特率，默认 115200\n",
      "  loginUsername: \"root\" # 串口登录用户名\n",
      "  loginPassword: \"root\" # 串口登录密码\n",
      "  keyProvider:\n",
      "    mode: \"file\"\n",
      "    challengeFilePath: \"./.embedded/configs/challenge.txt\" # 相对 cwd\n",
      "    keyFilePath: \"./.embedded/configs/password_input.txt\" # 相对 cwd\n",
      "    pollInterval: 500\n",
      "    timeout: 120000\n",
      "  # ── uboot 子段（serial_enter_uboot 检测配置，全部可选，留空用默认值）──\n",
      "  # 字段值直接写 JavaScript 正则源码字符串，由 new RegExp(source, flags) 构造。\n",
      "  # YAML 双引号字符串中反斜杠必须双写：写 \"\\\\s+\" 而非 \"\\s+\"（详见 docs/regex-guide.md）。\n",
      "  # 也可用单引号字符串避免双写：'\\s+' 即字面量 \\s+。\n",
      "  # 不配置整个 uboot 子段时，三组规则回退到内置默认值（行为等价改动前实现）。\n",
      "  uboot:\n",
      "    # autoboot 提示正则数组，按数组顺序匹配；构造时自动带 i 标志（大小写不敏感）。\n",
      "    # 含 \"Ctrl+c\" 字样 → 发送 \\x03；含 \"Ctrl+u\" → 发送 \\x15；其余 → 发送换行。\n",
      "    autobootPrompts:\n",
      "      - \"Hit\\\\s+Ctrl\\\\+u\\\\s+to\\\\s+stop\\\\s+autoboot\"\n",
      "      - \"Hit\\\\s+any\\\\s+key\\\\s+to\\\\s+stop\\\\s+autoboot\"\n",
      "    # 命令提示符正则，命中即判成功（主层）；构造时无 flags（=> 和 U-Boot> 固定大小写）。\n",
      "    # 默认值能认 => 和 U-Boot> 两种结尾。常见厂商提示符（按板子实际选一种）：\n",
      "    #   prompt: \"=>\"                          # 标准 U-Boot（最常见）\n",
      "    #   prompt: \"Marvell>>\"                   # Marvell 平台\n",
      "    #   prompt: \"hisilicon#\"                  # 海思平台\n",
      "    #   prompt: \"sunxi#\"                      # 全志平台\n",
      "    #   prompt: \"STM32MP>\"                    # STM32MP1/MP15\n",
      "    #   prompt: \"ZynqMP>\"                     # Xilinx ZynqMP\n",
      "    #   prompt: \"rk35xx#\"                     # Rockchip U-Boot\n",
      "    # 多板子共用配置时，用 (?:A|B) 联合，并用 $ 锚定末尾：\n",
      "    #   prompt: \"(?:=>|Marvell>>|hisilicon#)\\\\s*$\"\n",
      "    prompt: \"(?:=>|U-Boot>)\\\\s*$\"\n",
      "    # 提示符未命中时，发 printenv 验证的环境变量键（纯字面量，不走正则）。\n",
      "    verifyEnvKeys:\n",
      "      - \"baudrate\"\n",
      "      - \"bootdelay\"\n",
    ].join(""),
  },
  {
    dest: "remote-start-mcp.bat",
    content: [
      "@echo off\n",
      "REM ============================================================\n",
      "REM MCP Server launcher (shared by local Claude and remote SSH)\n",
      "REM\n",
      "REM Purpose: pin the working directory and 5 environment variables\n",
      "REM          so that whether started locally or via ssh from Linux,\n",
      "REM          the node process always has the same env as a local\n",
      "REM          Claude launch. Paths are relative to cwd, which is\n",
      "REM          anchored to the project root by the cd /d below.\n",
      "REM\n",
      "REM Usage:\n",
      "REM   - Local: double-click, or invoked by local .mcp.json\n",
      "REM   - Remote: set as the ssh remote command in Linux .mcp.json\n",
      "REM ============================================================\n",
      "\n",
      "REM Anchor cwd to this script's project root (%~dp0 ends with \\)\n",
      "cd /d \"%~dp0\"\n",
      "\n",
      "REM Environment variables (keep in sync with .mcp.json env block)\n",
      "set DEVICE=board-b\n",
      "set BOARD_CONFIG_PATH=./.embedded/configs/config.yaml\n",
      "set LOG_SAVE=1\n",
      "set LOG_DIR=./.embedded/log\n",
      "set SAVE2FILE_PATH=./.embedded/log\n",
      "\n",
      "REM Launch MCP server (stdio transport)\n",
      "node bin\\embedded-mcp-toolkit-cli.js\n",
    ].join(""),
  },
  {
    dest: ".embedded/configs/challenge.txt",
    content: [

    ].join(""),
  },
  {
    dest: ".embedded/configs/password_input.txt",
    content: [

    ].join(""),
  },
];
